" 
" File: .vimrc
" Author: Zack Fleischman
"

" Plugins and Key Mappings
source ~/.vimplugins
source ~/.vimmappings
source ~/.vimpluginmappings

" Syntax highlighting
syntax on   

" Show line numbers
set number  

" Disable errorbells
set visualbell
set t_vb=

" History Count
set history=1000
set undolevels=1000

" Visual Menu for file completion
set wildmenu
set wildmode=list:longest

" Tabs and Indents
set tabstop=4
set shiftwidth=4
set softtabstop=4
set backspace=2
set expandtab   " use spaces instead of tabs.
set smarttab    " let's tab key insert 'tab stops', and bksp deletes tabs.
set shiftround  " tab / shifting moves to closest tabstop.
set autoindent  " Match indents on new lines.
set smartindent " Intellegently dedent / indent new lines based on rules.

" We have VCS -- we don't need this stuff.
set nobackup " We have vcs, we don't need backups.
set nowritebackup " We have vcs, we don't need backups.
set noswapfile " They're just annoying. Who likes them?

" Don't nag me when hiding buffers
set hidden " allow me to have buffers with unsaved changes.
set autoread " when a file has changed on disk, just load it. Don't ask.

" Make search more sane
set ignorecase  " case insensitive search
set smartcase   " If there are uppercase letters, become case-sensitive.
set incsearch   " live incremental searching
set showmatch   " live match highlighting
set hlsearch    " highlight matches
set gdefault    " use the `g` flag by default.

" Set Color Mode
set t_Co=256

" Allow the cursor to go anywhere in visual block mode.
set virtualedit+=block
