" 
" File: .vimrc
" Author: Zack Fleischman
"

" Remap leader to the space bar. Do this before sourcing any mappings
let mapleader="\<Space>"

" Plugins and Key Mappings
source ~/.vimplugins
source ~/.vimpluginmappings

" ===========================
" KEY MAPPINGS
" ===========================

" So we don't have to reach for escape to leave insert mode.
inoremap jk <esc>

" Enter key goes to the end. Useful for line navigation. Enter the line # then
" press Enter
nnoremap <CR> G

" Switch mark jumpers
nnoremap ' `
nnoremap ` '

" Switch go to beginning of line / end of whitespace
nnoremap 0 ^
nnoremap ^ 0

" Bindings for easy split nav
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" LEADER MAPPINGS
" ---------------

" Split Panes
noremap <leader>v <C-w>v    " create new vsplit, and switch to it.
noremap <leader>s <C-w>s    " create new hsplit, and switch to it.

" Saving and Quiting
noremap <leader>w :w<CR>    " Save
noremap <leader>e :wq<CR>   " Save and quit
noremap Q :q<CR>            " Quit
noremap <leader>Q :q<CR>    " Quit
noremap q :q!<CR>           " Force Quit
noremap <leader>q :q!<CR>   " Force Quit

" Undo
noremap <leader>u <C-r>     " Undo

" Modify .vimrc
noremap <leader>t :vsplit<CR>:e ~/.vimrc<CR>           " Edit .vimrc
noremap <leader>T :source ~/.vimrc<CR>      " Apply .vimrc

" Turns off search highlight
noremap <leader><F5> :nohlsearch<CR>     

" Delete line
noremap <leader>d ^d$

" Tabs
map <F6> :tabedit 
map <F8> :tabn<CR>  " Next Tab
map <F7> :tabp<CR>  " Previous Tab

" Replace text
noremap <leader>r :%s//g<left><left>
noremap <leader>R :%s//gc<left><left><left>

" Goto mark
noremap gm m

" Format whole file
map <leader>= gmzgg=G`z

"====================
" Settings
"====================

" Syntax highlighting
syntax on   

" Show line numbers
set number  

" Disable errorbells
set visualbell
set t_vb=

" History Count
set history=1000
set undolevels=1000

" Visual Menu for file completion
set wildmenu
set wildmode=list:longest

" Tabs and Indents
set tabstop=4
set shiftwidth=4
set softtabstop=4
set backspace=2
set expandtab   " use spaces instead of tabs.
set smarttab    " let's tab key insert 'tab stops', and bksp deletes tabs.
set shiftround  " tab / shifting moves to closest tabstop.
set autoindent  " Match indents on new lines.
set smartindent " Intellegently dedent / indent new lines based on rules.

" We have VCS -- we don't need this stuff.
set nobackup " We have vcs, we don't need backups.
set nowritebackup " We have vcs, we don't need backups.
set noswapfile " They're just annoying. Who likes them?

" Don't nag me when hiding buffers
set hidden " allow me to have buffers with unsaved changes.
set autoread " when a file has changed on disk, just load it. Don't ask.

" Make search more sane
set ignorecase  " case insensitive search
set smartcase   " If there are uppercase letters, become case-sensitive.
set incsearch   " live incremental searching
set showmatch   " live match highlighting
set hlsearch    " highlight matches
set gdefault    " use the `g` flag by default.

" Set Color Mode
set t_Co=256

" Allow the cursor to go anywhere in visual block mode.
set virtualedit+=block

