#!/bin/bash

# Loop over all the files in the "dotfiles" directory 
# and make a symlink in ~
echo "Copying over symlinks for dot files"
echo "-----------------------------------"
DOT_FILES=dotfiles/*
for f in $DOT_FILES
do
    # Strip the path
    file=$(basename "$f")

    # Create a dot file symlink in the home folder	
    echo "Creating symlink for ~/.$file"
    PWD=$(pwd)
    ln -sfn $PWD/$f ~/.$file
done

# Install Vundle
echo ""
echo "Installing Vundle"
echo "-----------------"
if ! [ -e ~/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
else
    echo "Vundle is already installed!"
fi

# Install Oh-My-Zsh and my custom themes
echo ""
echo "Installing oh-my-zsh"
echo "--------------------"
source scripts/installOhMyZsh

# Install Homebrew
echo ""
echo "Installing Homebrew"
echo "-------------------"
source scripts/setupHomebrew

# Install Ag
echo ""
echo "Installing Ag"
echo "-------------"
brew install the_silver_searcher

echo ""
echo "Done!"
