#!/bin/bash

# Loop over all the files in the "dotfiles" directory 
# and make a symlink in ~
DOT_FILES=dotfiles/*
for f in $DOT_FILES
do
    # Strip the path
    file=$(basename "$f")

    # Create a dot file symlink in the home folder	
    echo "Creating symlink for ~/.$file"
    PWD=$(pwd)
    ln -sfn $PWD/$f ~/.$file
done

# Install Vundle
echo "Installing Vundle..."
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# Install Oh-My-Zsh and my custom themes
source scripts/installOhMyZsh

# Install Ag
brew install the_silver_searcher

echo "Done!"
