#!/bin/bash
# Creates a new ipython profile and then links our existing profile to it
ipython profile create
ln -sfn ~/repos/config/ipython/ipython_config.py ~/.ipython/profile_default/ipython_config.py
