#!/bin/sh

# Test to see if zshell is installed. 
install_zsh () {
    if ! [ -f /bin/zsh -o -f /usr/bin/zsh ]; then
        # If zsh isn't installed, get the platform of the current machine
        platform=$(uname);
        # If the platform is Linux, try an apt-get to install zsh and then recurse
        if [[ $platform == 'Linux' ]]; then
            sudo apt-get install zsh
            install_zsh
            # If the platform is OS X, tell the user to install zsh :)
        elif [[ $platform == 'Darwin' ]]; then
            echo "Please install zsh, then re-run this script!"
            exit
        fi
    fi
}
install_zsh

# Install oh-my-zsh if it isn't yet
if ! [ -d ~/.oh-my-zsh ]; then
    echo "Installing oh-my-zsh..."
    curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
fi

# Install custom oh-my-zsh profiles
PROFILES=zsh_profiles/*
for f in $PROFILES
do
    # Strip the path
    file=$(basename "$f")

    # Create a dot file symlink in the home folder	
    echo "Creating symlink for ~/.oh-my-zsh/custom/$file"
    PWD=$(pwd)
    ln -sfn $PWD/$f ~/.oh-my-zsh/custom/$file
done
