#!/bin/sh

source ./installDotFiles.shared

# Create symlinks for dot files
echo "-------------------------"
echo "Installing mac dotfiles"
echo "-------------------------"
DOT_FILES=../dotfiles.mac/*
for f in $DOT_FILES
do
    # Strip the path
    file=$(basename "$f")

    # Create a dot file symlink in the home folder	
    echo "Creating symlink for ~/.$file"
    PWD=$(pwd)
    echo "ln -sfn $PWD/$f ~/.$file"
    ln -sfn $PWD/$f ~/.$file
    echo ""
done
