# Pull in from the common zshrc (OS agnostic)
source $HOME/.zshrc.common

# Mac specific Path stuff
export PATH="$PATH:/usr/local/homebrew/bin"

# Source Mac Specific Scripts
# <None right now>

# Autojump
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# Open Mac Apps
alias fire='open -a /Applications/Firefox.app'
alias chrome='open -a /Applications/Google\ Chrome.app'
alias ij='open -a /Applications/IntelliJ\ IDEA\ 12.app'
alias vlc='open -a /Applications/VLC.app'

##############################
# Mac Specific Command Aliases
##############################

# Kill finder
alias kf='killall -KILL Finder'

# Reindex spotlight
alias spotlight='sudo mdutil -E /'

# Replace Vim with MacVim, specifically for YouCompleteMe Vim plugin
alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
export VIMRUNTIME=/Applications/MacVim.app/Contents/Resources/vim/runtime

# Tmux for it to work right with mac terminal colors
alias tmux='tmux -2'

# Backup Script
alias bu='bp;backup.mac'

# Homebrew
alias bin='brew install'
alias bun='brew uninstall'
alias ci='brew cask install' 
alias cs='brew cask search' 

# Notifications
alias n='~/repos/scripts/osx/notify'

# Alias 'python_watch' to the osx version
alias python_watch='python_watch_osx'

alias unity=/Applications/Unity/Unity.app/Contents/MacOS/Unity

alias txt='pbpaste | text'  # text myself whats in the clipboard

# LaTeX
#alias pdflatex='/Library/TeX/Root/bin/x86_64-darwin/pdflatex'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
