# Pull in from the common zshrc (OS agnostic)
source $HOME/.zshrc.common

# Mac specific Path stuff
export PATH="$PATH:/usr/local/homebrew/bin"
export PATH=/opt/homebrew/bin:$PATH


# Source Mac Specific Scripts
# <None right now>

# Autojump
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# Moving forward and backward by words and lines (NOTE: Need to setup in iterm2 preferences too)
bindkey "[D" backward-word
bindkey "[C" forward-word
bindkey "^[a" beginning-of-line
bindkey "^[e" end-of-line
bindkey "^D" backward-kill-line
bindkey "^H" backward-kill-word

# Open Mac Apps
alias fire='open -a /Applications/Firefox.app'
alias chrome='open -a /Applications/Google\ Chrome.app'
alias ij='open -a /Applications/IntelliJ\ IDEA\ 12.app'
alias vlc='open -a /Applications/VLC.app'

##############################
# Mac Specific Command Aliases
##############################

# Kill finder
alias kf='killall -KILL Finder'

# Reindex spotlight
alias spotlight='sudo mdutil -E /'

# Tmux for it to work right with mac terminal colors
alias tmux='tmux -2'

# Backup Script
alias bu='bp;backup.mac'

# Notifications
alias n='~/repos/scripts/osx/notify $?'

alias txt='pbpaste | text'  # text myself whats in the clipboard

# LaTeX
#alias pdflatex='/Library/TeX/Root/bin/x86_64-darwin/pdflatex'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Add fuzzy file finding. ^t for files, ^r for history
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'

source $HOME/.aurorarc
alias es='vim $HOME/.aurorarc'

export PATH="/usr/local/opt/mongodb-community@4.0/bin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
