# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME=burner

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

autoload run-help
HELPDIR=/usr/local/share/zsh/help

# zsh options
setopt no_histverify

# My Environment Variables
export MINE=`cat ~/.mine`

# Tmux window naming
DISABLE_AUTO_TITLE=true

# Paths
SCRIPT_PATHS=$(find ~/repos/scripts/ -type d | grep -v "\.git" | sed "s,/$,," | tr '\n' ':')
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/scripts:$SCRIPT_PATHS"
export PATH="$PATH:/usr/texbin"
export PYTHONPATH="$PYTHONPATH:$HOME/repos/zfleischman/util:$HOME/repos/zfleischman/shellplus:$HOME/repos/scripts/zpython:$HOME/repos/scripts/django"
export PYTHONDONTWRITEBYTECODE=1
alias setpyc='export PYTHONDONTWRITEBYTECODE=0'
alias unsetpyc='export PYTHONDONTWRITEBYTECODE=1'

# Source Scripts
source ~/repos/scripts/util/findfile
source ~/repos/scripts/util/findstring
source ~/repos/scripts/util/exportColors
if [ -f ~/.growlrc ]; then
    source ~/.growlrc
fi

# Autojump
. /usr/share/autojump/autojump.sh

# Ensure running python 3
#alias python='python3'
#alias pip='pip3'
alias pudb='python -m pudb.run'

# Open Apps
alias fire='open -a /Applications/Firefox.app'
alias ch='open -a /Applications/Google\ Chrome.app'
alias ij='open -a /Applications/IntelliJ\ IDEA\ 12.app'
alias vlc='open -a /Applications/VLC.app'

# Command Shortcuts
alias sz='source ~/.zshrc'
alias ez='vim ~/.zshrc'
alias eg='vim ~/.gitconfig'
alias ev='vim ~/.vimrc'
alias ep='vim ~/.vimplugins'
alias ls="echo -e '\e[1;30m'`pwd`; echo -en '\e[0m';ls --color=tty"
alias ll='ls -la'
alias zb='zyngabackup'
alias pp='prettyprint'
alias htop='sudo htop'
alias mem='top -o mem'
alias cpu='top -o cpu'
alias x='chmod 755 '
alias pudb='python -m pudb.run'
alias pi='ping google.com'
alias py='ipython -i ~/repos/scripts/zpython/zutil.py'
alias pyc='find . -name "*.pyc" -type f -delete'
alias zutil='vim ~/repos/scripts/zpython/zutil.py'

alias ve='virtualenv virt_env/virt1'

# Git
alias d='git difftool'
alias dd='git --no-pager diff --color=always'
alias ddd='git diff --color=always'
alias dm='git diff master'
alias dmv='git difftool master'
alias s='git status'
alias br='git branch -r'
alias stashlist='git stash list | awk '"'"' BEGIN { print "" } {print "",$0} END { print "" }'"'"''
alias stash='git stash'
alias pop='git stash pop'
alias l='gitlog -10'
alias l2='gitlog -20'
alias l3='gitlog -30' 
alias l4='gitlog -40'
alias ldate='gitlogdate -10'
alias l2date='gitlogdate -20'
alias l3date='gitlogdate -30'
alias l4date='gitlogdate -40'
alias lx='gitlog'
alias lxdate='gitlogdate'
alias gf='git fetch'
alias r='git pull --rebase'
alias cbranch='git rev-parse --abbrev-ref HEAD'
alias p='git push origin `git rev-parse --abbrev-ref HEAD`'
alias c='git commit -am'
alias u='git pull'
alias has='git branch --contains'
alias reset='git reset --hard HEAD'
alias tool1='git config --global diff.tool Kaleidoscope'
alias tool2='git config --global diff.tool p4mergetool'
alias merge='git mergetool'
alias cm='git commit --author="Zack Fleischman <zFleischman@gmail.com>"'
alias aa='git commit --amend --author "Zack Fleischman <zFleischman@gmail.com>" --no-edit'

# Vim Tag Jump
alias tj='vim -t'

# Code Collab
alias lr='ccollab actionitems'

# Resumé
alias resume='pdflatex ~/repos/resume/src/resume.tex;mv ~/repos/resume/src/resume.pdf ~/repos/resume/resume.pdf;open ~/repos/resume/resume.pdf'

# BikeCommute
alias bike='python ~/repos/BikeCommuter/BikeCommute.py'

# Growl notifier
alias g='ssh zfleischman@$GROWLR_IP /Users/zfleischman/repos/scripts/osx/growl'

# Fin
alias fin='python ~/repos/FinMessenger/Fin.py'

################
# Path Shortcuts
################

# All Repos
alias a='cd ~/repos'

# Wonderdome
alias w='cd ~/repos/wonderdome'
alias wm='cd ~/repos/wonderdome/src/playasophy/wonderdome/mode'


# Scripts
alias q='cd ~/repos/scripts'

# Config
alias ac='cd ~/repos/config'


#################
## Functions
#################

# Extract from a zipped file
extract () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xvjf $1 && cd $(echo $1 | sed 's/.tar.bz2//')    ;;
            *.tar.gz)    tar xvzf $1 && cd $(echo $1 | sed 's/.tar.gz//')    ;;
            *.bz2)       bunzip2 $1 && cd $(echo $1 | sed 's/.bz2//')    ;;
            *.rar)       unrar x $1 && cd $(echo $1 | sed 's/.rar//')    ;;
            *.gz)        gunzip $1 && cd $(echo $1 | sed 's/.gz//')    ;;
            *.tar)       tar xvf $1 && cd $(echo $1 | sed 's/.tar//')    ;;
            *.tbz2)      tar xvjf $1 && cd $(echo $1 | sed 's/.tbz2//')    ;;
            *.tgz)       tar xvzf $1 && cd $(echo $1 | sed 's/.tgz//')    ;;
            *.zip)       unzip $1 && cd $(echo $1 | sed 's/.zip//')    ;;
            *.Z)         uncompress $1 && cd $(echo $1 | sed 's/.Z//')    ;;
            *.7z)        7z x $1 && cd $(echo $1 | sed 's/.7z//')    ;;
            *)           echo "don't know how to extract '$1'..." ;;
        esac
    else
        echo "'$1' is not a valid file!"
    fi
}

# Ctrl-Z to switch between vim and the command line
fancy-ctrl-z () {
    if [[ $#BUFFER -eq 0 ]]; then
        BUFFER="fg"
        zle accept-line
    else
        zle push-input
        zle clear-screen
    fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z


###################
## External Sources
###################
source ~/.counsylrc
